//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 竞赛学生系统
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCS_SignUp
    {
        public int id { get; set; }
        public string 姓名 { get; set; }
        public string 班级 { get; set; }
        public int 学号 { get; set; }
        public string 学年成绩 { get; set; }
        public int 电话 { get; set; }
        public string 比赛项目 { get; set; }
        public string 类别 { get; set; }
        public string 邮箱 { get; set; }
        public string 报名时间 { get; set; }
        public string 团队人员姓名 { get; set; }
        public int 审阅状态 { get; set; }
        public Nullable<int> 职工号 { get; set; }
    }
}
