//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 竞赛老师系统
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentsCompetitionSystemEntities : DbContext
    {
        public StudentsCompetitionSystemEntities()
            : base("name=StudentsCompetitionSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SCS_Catogary> SCS_Catogary { get; set; }
        public DbSet<SCS_Competition> SCS_Competition { get; set; }
        public DbSet<SCS_Login> SCS_Login { get; set; }
        public DbSet<SCS_SignUp> SCS_SignUp { get; set; }
        public DbSet<SCS_Teacher> SCS_Teacher { get; set; }
        public DbSet<SCS_TeacherLogin> SCS_TeacherLogin { get; set; }
    }
}
