//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 竞赛老师系统
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCS_Message
    {
        public int id { get; set; }
        public string 发件人 { get; set; }
        public string 时间 { get; set; }
        public string 内容 { get; set; }
    }
}
