//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 竞赛老师系统
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCS_Competition
    {
        public int id { get; set; }
        public string 名称 { get; set; }
        public string 竞赛名称 { get; set; }
        public string 类别 { get; set; }
        public string 内容 { get; set; }
        public string 发布时间 { get; set; }
        public string 截止时间 { get; set; }
        public string 逻辑删除 { get; set; }
        public int 职工号 { get; set; }
    }
}
