//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 竞赛老师系统
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCS_Teacher
    {
        public int id { get; set; }
        public string 姓名 { get; set; }
        public string 职工号 { get; set; }
        public Nullable<int> 手机号码 { get; set; }
        public string 邮箱 { get; set; }
        public string 办公地址 { get; set; }
    }
}
