//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_SCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCS_Login
    {
        public int id { get; set; }
        public Nullable<int> 学号 { get; set; }
        public string 密码 { get; set; }
        public string 姓名 { get; set; }
    }
}
